version: "3.8"
services:
    bot:
        build: 
            context: .
        container_name: "swipe-api-bot"
        restart: always
        environment: 
            - .env
        depends_on: 
            - redis
    redis:
        image: redis:6.0-alpine
        container_name: "swipe_api-redis"
        hostname: redis
        volumes:
            - "redis_data:/data"
        command: "redis-server"

volumes:
    redis_data:
